### ISSUE TITLE
Can we use this for 2016 hacktoberfest?

### ISSUE THREAD

**Issue by eddiejaoude** [erikaheidi/hacktoberfest-verify#10]

**Comment by polaroi8d** [comment]
@eddiejaoude there is the 2016 verifycation on #8 PR :) or u can use easily this site >> [https://hacktoberfestchecker.herokuapp.com/](https://hacktoberfestchecker.herokuapp.com/)

**Comment by eddiejaoude** [comment]
Thanks 👍
